### ISSUE TITLE
matlab2018B does not have mexopts.sh

### ISSUE THREAD

**Issue by bbaserdem** [petronny/matlab#2]
I have been trying to include some options from yor pkgbuild in mine, and im working on r2018b at the moment.

I noticed that mexoopts.sh does not exist in `bin` anymore. However, there is a `bin/glnx64/mexopts/` directory that contains some xml files. Did you deal with these at all in terms of setting GCC to gcc6 from aur?

**Comment by petronny** [comment]
I'm downloading the iso of r2018b now.
I heard that matlab has changed the way to set up mex options.
I will try to find a proper way to set them in r2018b.

**Comment by bbaserdem** [comment]
If you find out a way to do it in the PKGBUILD, I can also adapt it. For now, the setenv function in startup.m works in my installation.

**Comment by petronny** [comment]
```
When running the installer with an input file, you must specify the full path to a license file using the licensePath option.
```
So we have to set `_networkinstall=true`.

**Comment by petronny** [comment]
About the xmls, first run
```
>> cc = mex.getCompilerConfigurations('C','Selected')
cc = 
    CompilerConfiguration with properties:
               Name: 'gcc'
       Manufacturer: 'GNU'
           Language: 'C'
            Version: ''
           Location: '/usr/bin/gcc'
          ShortName: 'gcc'
           Priority: 'A'
            Details: [1×1 mex.CompilerConfigurationDetails]
         LinkerName: ''
      LinkerVersion: ''
             MexOpt: '/home/anicastro/.matlab/R2017a/mex_C_glnxa64.xml'
```
to find out which xml you are using.
Then edit `which gcc` to `which gcc-6` in the locationFinder session should work.

**Comment by petronny** [comment]
About the xmls, first run
```
>> cc = mex.getCompilerConfigurations('C','Selected')
cc = 
    CompilerConfiguration with properties:
               Name: 'gcc'
       Manufacturer: 'GNU'
           Language: 'C'
            Version: ''
           Location: '/usr/bin/gcc'
          ShortName: 'gcc'
           Priority: 'A'
            Details: [1×1 mex.CompilerConfigurationDetails]
         LinkerName: ''
      LinkerVersion: ''
             MexOpt: '/home/anicastro/.matlab/R2017a/mex_C_glnxa64.xml'
```
to find out which xml you are using.
Then edit `which gcc` to `which gcc-6` in the locationFinder session should work.

**Comment by petronny** [comment]
About the xmls, first run
```
>> cc = mex.getCompilerConfigurations('C','Selected')
cc = 
    CompilerConfiguration with properties:
               Name: 'gcc'
       Manufacturer: 'GNU'
           Language: 'C'
            Version: ''
           Location: '/usr/bin/gcc'
          ShortName: 'gcc'
           Priority: 'A'
            Details: [1×1 mex.CompilerConfigurationDetails]
         LinkerName: ''
      LinkerVersion: ''
             MexOpt: '/home/anicastro/.matlab/R2017a/mex_C_glnxa64.xml'
```
to find out which xml you are using.
Then edit `which gcc` to `which gcc-6` in the locationFinder session should work.

**Comment by bbaserdem** [comment]
I'm not with my main computer atm, but I will try this on my workstation tomorrow!

**Comment by bbaserdem** [comment]
And it works great!
